version: '2.1'

services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    volumes:
      - .:/crypto-plants
      - .env.example:/crypto-plants/.env
      - /crypto-plants/node_modules
    environment:
      - DOTENV_PATH=.env

  database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432

  test-database:
    container_name: database
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432

  test:
    extends: base
    environment:
      - TEST_SUITE
      - NODE_ENV=test
    command: yarn test-${TEST_SUITE}
    links:
      - test-database

  server:
    extends: base
    command: yarn dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
