version: '2.1'

services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    volumes:
      - .:/crypto-plants
      - .env.example:/crypto-plants/.env
      - /crypto-plants/node_modules
    environment:
      - DOTENV_PATH=.env

  database:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_PASSWORD=crypto-plants123$$
    ports:
      - 5432

  test-database:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_PASSWORD=cipagarme123$$
    ports:
      - 5432

  test:
    extends: base
    environment:
      - TEST_SUITE
      - NODE_ENV=test
    command: yarn test-${TEST_SUITE}
    links:
      - database

  server:
    extends: base
    command: yarn start
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
